name: CAREERMEDIC
favicon: null
layout_spectrum: 0.74952
typography_spectrum: 0.1334
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: CAREERMEDIC
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#99c71d'
    - '#7e7e7e'
    - '#c7df71'
    - '#b2b2b2'
  brandStrength: 0.75
  lightness: 0.5625
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
