name: CAREERMEDIC
favicon: null
layout_spectrum: 0.99904
typography_spectrum: 0.50384
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: CAREERMEDIC
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FAFAFA'
    - '#AFD135'
    - '#7E7E7E'
    - '#B2B3B6'
  brandStrength: 0
  lightness: 0.5
  saturation: 1
  rhythmicContrast: 0.5
purpose: []
