collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
typography_spectrum: 0.7206646
color:
  saturation: 0.03066861
  brandStrength: 0.7897155
  lightness: 0.07972275
  brandColors:
    - '#FAFAFA'
    - '#AFD135'
    - '#7E7E7E'
    - '#B2B3B6'
  rhythmicContrast: 0.7709698
layout_spectrum: 0.8330523
name: CAREERMEDIC
